version: '3.8'

services:
  db:
    build:
      context: ./database
    container_name: db-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_esiea
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "mysql -u test -ptest -e 'SELECT 1;'"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: ./backend
    container_name: backend-container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: sh -c "python myproject/manage.py migrate && python myproject/manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "3001:3000"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
