# Generated by Django 5.1.4 on 2024-12-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbPlayers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('club', models.CharField(blank=True, db_column='Club', max_length=50, null=True)),
                ('birth_year', models.IntegerField(blank=True, db_column='AnneeNaissance', null=True)),
            ],
            options={
                'db_table': 'tb_players',
                'managed': True,
            },
        ),
    ]
